const About = () => {
	return (
		<div className="About">
			<h1>A propos</h1>
			<div className="About-content">
				<p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eum ea exercitationem beatae, est repellendus similique culpa labore dolorem architecto libero et saepe, nostrum perferendis aspernatur dolore consequuntur tempora rerum quas ad quis id! Eos aut recusandae voluptatem in libero perspiciatis illum voluptatum, nihil modi culpa optio reiciendis magni dolorum sed est vitae sunt magnam quam fugit! Magnam aperiam excepturi sunt dolores quisquam et sequi voluptatum, deleniti, eligendi temporibus, voluptates repellat. Quae cumque sequi quas nobis porro ullam magnam vel fugiat illo harum molestias unde natus maiores nulla itaque, iusto ipsa asperiores, reiciendis dolorem corporis facere. Deleniti ipsam maiores ut obcaecati!</p>
				<p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Labore veniam reiciendis, debitis ullam id odio dolorum quo. Vitae tempore beatae quibusdam ratione ullam assumenda voluptatum ipsum odit a, dolores laboriosam eaque quaerat officiis amet et accusamus neque temporibus vel inventore tenetur dolorum eligendi impedit? Quas corrupti rem molestiae pariatur? Ipsum possimus deserunt libero est, omnis aut nemo molestias iste, eaque similique obcaecati nesciunt fugit nihil distinctio quo cum dolor, provident sunt? Tempore adipisci repellat laborum odio est deserunt unde placeat, necessitatibus veritatis ducimus maiores perferendis exercitationem quasi sint? Saepe minus sequi nisi. Placeat beatae natus iure. Incidunt corporis voluptate cumque quaerat mollitia explicabo, est nam. A unde corrupti officia suscipit! Placeat nisi eaque quia natus! Mollitia sapiente dignissimos consequuntur aliquam explicabo enim beatae animi sunt? Labore eveniet placeat quo? Accusamus ut eligendi totam non officia praesentium velit quibusdam nam quod pariatur odit fugit sequi, quam laudantium beatae earum? Incidunt facere magni quia dignissimos dicta tempora, laudantium quae dolores optio, ratione deserunt praesentium quas quisquam perspiciatis magnam omnis velit nisi aspernatur. Dolore laboriosam mollitia repudiandae doloribus possimus nisi, officiis vel odio praesentium error accusamus, dolor aliquam ea qui sequi. Asperiores, non nisi reprehenderit laboriosam corporis in culpa ad perferendis tempore tenetur!</p>
			</div>
		</div>
	);
};

export default About;